import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
            <title>Dimitri Marco Portofolio</title>
            <meta name="description" content="Generated by crea" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Intro */}
        <main className="bg-gray-900 text-teal-600 min-h-screen">
            {/* Intro */}
            <nav className="w-48 fixed left-0 top-0 h-screen px-6 py-10 flex flex-col justify-center gap-6">
                <a href="#background">
                    Background
                </a>
                <a href="#experience">
                    Experience  
                </a>
            </nav>
            {/* Intro */}
            <section className="min-h-screen flex justify-center items-center"> 
                <div className="text-center p-10">
                    <h1 className="text-4xl font-">
                        Kevin Lai
                    </h1>
                </div>
                <div className="text-center p-10">
                    <h2 className="text-4xl font-">
                        Kevin Lai
                    </h2>
                </div>
            </section>
            {/* Background */}
            <section id="background">
            </section>
            {/* Experience */}
                <div className="text-center p-10">
                    <h1 className="text-teal-600 text-4xl font-">
                        Kevin Lai
                    </h1>
                </div>
            <section id="experience">

            </section>
        </main>
    </div>
  );
}

