import Head from "next/head";
import {useState, useEffect } from "react";
import FadeIn from "../pages/FadeIn";
import Image from "next/image";
import IconGitHub from "../public/github";
import IconInstagram from "../public/instagram";    
import IconLinkedin from "../public/linkedin";
import IconWordPress from "../public/wordpress";
import IconLink from "../public/link";
import IconK from "../public/logo";
import IconNorca from "../public/norca";
import LogoLoader from "../pages/LogoLoad";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
    const timer = setTimeout(() => {
        setIsLoading(false);
    }, 2450);

    return () => clearTimeout(timer);
    }, []);

    if (isLoading) {
    return (
        <div className="min-h-screen fixed inset-0 z-[9999] grid place-items-center bg-slate-950">
            <LogoLoader />
        </div>
    );
    }

  return (
    <div className={darkMode ? "dark" : ""}>
        <Head>
            <title>Kevin Lai Portfolio</title>
            <meta name="description" content="Generated by react and tailwind" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="text-teal-500 min-h-screen">
            <nav className="flex z-100 w-48 fixed left-0 top-0 h-10 px-2 py-4 gap-6">
                <a href="#intro" className="cursor-pointer [font-family:var(--font-space)]">
                    <IconK className="mx-3 w-6 sm:w-8 lg:w-11 text-teal-500" />
                </a>
            </nav>
            <nav className="hidden lg:flex z-50 w-48 fixed left-0 top-0 h-screen px-6 py-10 flex-col justify-center gap-6">
                <a href="#background" className="cursor-pointer [font-family:var(--font-space)]">
                    About
                </a>
                <a href="#experience" className="cursor-pointer [font-family:var(--font-space)]">
                    Experience  
                </a>
                <a href="#projects" className="cursor-pointer [font-family:var(--font-space)]">
                    Projects  
                </a>
                <a href="#contact" className="cursor-pointer [font-family:var(--font-space)]">
                    Contact  
                </a>
            </nav>
            {/* Intro */}
            <FadeIn>
            <section id="intro" className="min-h-screen"> 
                <nav className="flex justify-between text-teal-700 px-2">
                    <div></div>
                    <div className="flex">
                        <a href="https://github.com/Dmitry-Oyawale" target="_blank" rel="noopener noreferrer">
                            <IconGitHub className="mx-2 my-4 w-6 sm:w-8 lg:w-11 hover:text-white transition" />
                        </a>
                        <a href="https://www.linkedin.com/in/kevin-lai-250339313/" target="_blank" rel="noopener noreferrer">
                            <IconLinkedin className="mx-2 my-4 w-6 sm:w-8 lg:w-11 hover:text-white transition" />
                        </a>
                        <a href="https://www.instagram.com/kevinlai483/" target="_blank" rel="noopener noreferrer">
                            <IconInstagram className="mx-2 my-4 w-6 sm:w-8 lg:w-11 hover:text-white transition" />
                        </a>
                    </div>
                </nav>
                <div className="px-6 mt-20 sm:px-10 lg:px-24 lg:mt-32 xl:px-96 xl:mt-35 flex flex-col justify-center">
                    <h3 className="text-[1.35-rem] [font-family:var(--font-space)]">
                        Hello, my name is
                    </h3>
                    <h1 className="py-2 text-gray-300 text-7xl sm:text-9xl [font-family:var(--font-space)]">
                        kevin Lai
                    </h1>
                    <h1 className="text py-2 font-bold text-gray-400 text-2xl">
                        Software Developer
                    </h1>
                    <h1 className="py-2 text-gray-400 text-2xl">
                        Student at Worcester Polytechnic Institute with full stack development experience, driven profoundly by career-oriented ambition and an avidity for building technological breadth. 
                    </h1>
                </div>
                <div className="flex justify-center norca-container">
                    <a href="#background">
                        <IconNorca className="mx-2 my-8 lg:my-16 w-6 sm:w-8 lg:w-11 hover:text-white transition" />
                    </a>
                </div>
            </section>
            </FadeIn>
            {/* Background */}
            <FadeIn>
            <section id="background" className="min-h-screen scroll-mt-24">
                <div className="px-6 sm:px-10 lg:px-24 xl:px-67">
                    <h1 className="text-6xl [font-family:var(--font-space)]">
                        about.
                    </h1>
                    <br></br>
                    <div className="text-gray-400 [font-family:var(--font-space)]">
                        <h2 className="text-sm w-1/2">
                             I’m a student at Worcester Polytechnic Institute dedicated to the field of Computer Science. The fast-paced, team-oriented school culture resonates with me as I am always open to forming new connections and seeking new opportunities, whether on or off-campus. Though I once harbored ambitions in web development, I find the current zeitgeist  conducive to furthering my interests in machine learning, cybersecurity, and robotics engineering, which I hope to double major in. 
                        </h2>
                        <h1 className="text-sm w-1/2 second-half-text">
                            My past work has revolved mainly around democratizing education for the 21st century world. At Tzu Chi I managed lesson logistics and technological troubleshooting for students in a language course, while at MyEdMaster I developed an app for SAT test practice to provide low-cost tutoring. My latest internship at Framingham Public Schools aims to vastly upscale English-language fluency for migrant families, via a web tool facilitating rapid, mass translation, parsing, and distribution of school content. 
                        </h1>
                        <br></br>
                        <h1 className="text-sm w-1/2">
                            In my free time I am keen to workout, listen to music, and go for a run or hike; at WPI I am involved in the run club and Association for Computing Machinery. I seek to travel more and actively take in the exciting world around us; I am also interested in history, philosophy, and economics. In the past I have run a personal blog to catalog my readings. 
                        </h1>
                        <br></br>
                        <br></br>
                        <div className="flex flex-col flex-wrap justify-center items-center text-center">
                            <h1 className="text-sm">
                                My current tech stack includes the following:
                            </h1>
                            <div className="flex flex-wrap text-sm mt-4 gap-10">
                                <ul>
                                    <li className="flex flex-wrap items-center stack-fade1"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        Python
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade2"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        Java
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade3"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        C
                                    </li>
                                </ul>
                                <ul className="text-sm">
                                    <li className="flex flex-wrap items-center stack-fade4"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        C++
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade5"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        SQL
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade6"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        Node.js
                                    </li>
                                </ul>
                                <ul className="text-sm">
                                    <li className="flex flex-wrap items-center stack-fade7"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        JavaScript
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade8"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        CSS
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade9"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        HTML
                                    </li>
                                </ul>
                                <ul className="text-sm">
                                    <li className="flex flex-wrap items-center stack-fade10"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        Django
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade11"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        React.js
                                    </li>
                                    <li className="flex flex-wrap items-center stack-fade12"> 
                                        <span className="text-teal-500 text-2xl mr-2">&#x2023;</span>
                                        Flask
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            </FadeIn>
            {/* Experience */}
            <FadeIn>
            <section id="experience" className="min-h-screen scroll-mt-24 mt-19 sm:mt-36 lg:mt-32">   
                <div className="px-6 sm:px-10 lg:px-24 xl:px-67">
                    <h1 className="text-6xl [font-family:var(--font-space)]">
                        experience.
                    </h1>
                    <br></br>
                    <div className="px-4 sm:px-8 lg:px-24 trans-container group relative overflow-hidden">
                        <div className="relative items-start gap-2 flex flex-col sm:flex-row">
                            <h1 className="text-1xl text-gray-400 w-50 shrink-0"> 
                                Jan. 2025 – Aug. 2025
                            </h1>
                            <div className="flex flex-col gap-3">
                                <div className="flex child-container justify-between">
                                    <h1 className="child-container text-[1.35rem] text-gray-200">
                                        Game Dev Intern · MyEdMaster
                                    </h1>
                                    <a href="https://www.myedmaster.com/" target="_blank" rel="noopener noreferrer">
                                        <IconLink className="w-7 text-gray-200 child-container hover:text-white transition" />
                                    </a>
                                </div>
                                <p className="text-1xl text-gray-400">
                                    Built an interactive SAT prep game used by students with React, Django, and PostgreSQL, featuring real-time gameplay, dynamic scoring, and multiplayer support via REST APIs and WebSockets. Implemented a weekly, category-based leaderboard (Math and Reading) with live data refresh and sub-second UI updates. Designed responsive, data-driven UI components and a clean, modular architecture to improve scalability and reduce maintenance overhead.
                                </p>
                                <div className="gap-2">
                                    <div className="flex flex-row flex-wrap justify-start gap-2 text-sm text-teal-400">
                                        <h3 className="mini-container">JavaScript</h3>
                                        <h3 className="mini-container">React.js</h3>
                                        <h3 className="mini-container">Python</h3>
                                        <h3 className="mini-container">SQL</h3>
                                        <h3 className="mini-container">Django</h3>
                                
                                        <h3 className="mini-container">Node.js</h3>
                                        <h3 className="mini-container">HTML</h3>
                                        <h3 className="mini-container">CSS</h3>
                                    </div>  
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="px-4 sm:px-8 lg:px-24 trans-container group relative overflow-hidden">
                        <div className="relative items-start gap-2 flex flex-col sm:flex-row">
                            <h1 className="text-1xl text-gray-400 w-50 shrink-0"> 
                                Sep. 2025 – Dec. 2025
                            </h1>
                            <div className="flex flex-col gap-3">
                                <div className="flex child-container justify-between">
                                    <h1 className="child-container text-[1.35rem] text-gray-200">
                                        Digital Content Intern · Framingham Public Schools
                                    </h1>
                                    <a href="https://www.framingham.k12.ma.us/" target="_blank" rel="noopener noreferrer">
                                        <IconLink className="w-7 text-gray-200 child-container hover:text-white transition" />
                                    </a>
                                </div>
                                <p className="text-1xl text-gray-400">
                                    Collaborated with three departments to digitize and organize multilingual Portuguese and English curriculum materials, processing 500+ files and developing a Python-based parsing tool using Beautiful Soup and Playwright to automate text extraction and tagging, improving workflow efficiency and reducing manual errors by 40%.
                                </p>
                                <div className="gap-2">
                                    <div className="flex flex-row justify-start gap-2 text-sm text-teal-400">
                                        <h3 className="mini-container">Python</h3>
                                        <h3 className="mini-container">HTML</h3>
                                        <h3 className="mini-container">CSS</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            </FadeIn>
            {/* Projects */}
            <FadeIn>
            <section id="projects" className="min-h-screen scroll-mt-24 ">  
                <div className="px-6 sm:px-10 lg:px-24 xl:px-67  text-gray-200 [font-family:var(--font-space)]">
                    <h1 className="text-6xl text-teal-500 [font-family:var(--font-space)]">
                            projects.
                    </h1>
                    <br></br>
                    <div className="px-4 sm:px-8 lg:px-24 site-container">
                        <div className="flex justify-between">
                            <h1 className="text-3xl">
                                Research Position Matcher
                            </h1>
                            <a href="https://github.com/Dmitry-Oyawale/projectphase3-querycrushers" target="_blank" rel="noopener noreferrer">
                                <IconLink className="w-7 hover:text-white transition" />
                            </a>
                        </div>
                        <br></br>
                        <h1 className="text-[.9rem]">
                            Built and deployed a full-stack Flask application on AWS that matches students with faculty research positions using profile-based recommendations, Auth0 authentication, and a PostgreSQL backend.
                        </h1>
                        <br></br>
                        <div className="w-1/2 text-gray-400 text-[.9rem] flex gap-6">
                            <p>Python</p>
                            <p>HTML</p>
                            <p>CSS</p>
                            <p>JavaScript</p>
                            <p>SQL</p>
                            <p>PostgreSQL</p>
                        </div>
                    </div>
                    <div className="px-4 sm:px-8 lg:px-24 site-container">
                        <div className="flex justify-between">
                            <h1 className="text-3xl">
                                Yelp Database app
                            </h1>
                            <a href="https://github.com/Dmitry-Oyawale/projectphase3-querycrushers" target="_blank" rel="noopener noreferrer">
                                <IconLink className="w-7 hover:text-white transition" />
                            </a>
                        </div>
                        <br></br>
                        <h1 className="text-[.9rem]">
                            A scalable PostgreSQL database for 100K+ Yelp records and a JavaFX application for interactive querying and visualization.
                        </h1>
                        <br></br>
                        <div className="w-1/2 text-gray-400 text-[.9rem] flex gap-6">
                            <p>Java</p>
                            <p>Python</p>
                            <p>CSS</p>
                            <p>SQL</p>
                            <p>PostgreSQL</p>
                        </div>
                    </div>
                    <div className="px-4 sm:px-8 lg:px-24 site-container">
                        <div className="flex justify-between">
                            <h1 className="text-3xl">
                                Python Notes Website
                            </h1>
                            <a href="https://github.com/Dmitry-Oyawale/Flask-Web-App-3" target="_blank" rel="noopener noreferrer">
                                <IconLink className="w-7 hover:text-white transition" />
                            </a>
                        </div>
                        <br></br>
                        <h1 className="text-[.9rem]">
                            A Python-based notes application using Flask with secure authentication, SQLAlchemy-backed data persistence, and a responsive user interface for managing personal notes.
                        </h1>
                        <br></br>
                        <div className="text-gray-400 text-[.9rem] flex flex-wrap gap-6">
                            <p>Python</p>
                            <p>CSS</p>
                            <p>HTML</p>
                            <p>JavaScript</p>
                            <p>Bootstrap</p>
                            <p>Jinja</p>
                            <p>Flask</p>
                            <p>SQL</p>
                        </div>
                    </div>
                </div>
            </section>
            </FadeIn>
            <FadeIn>
            <section id="contact" className="min-h-screen scroll-mt-24  mt-19 sm:mt-36 lg:mt-32">  
                <div className="px-6 sm:px-10 lg:px-24 xl:px-67  text-gray-200">
                    <h1 className="text-6xl text-teal-500 [font-family:var(--font-space)]">
                            contact.
                    </h1>
                    <br></br>
                    <br></br>
                    <u className="text-2xl flex justify-center">laikevin279@gmail.com</u>
                    <br></br>
                    <br></br>

                    <div className="text-gray-400 flex flex-col flex-wrap items-center gap-6">
                        <div className="flex flex-row flex-wrap gap-8">
                            <a href="https://github.com/Dmitry-Oyawale" target="_blank" rel="noopener noreferrer">
                                <IconGitHub className="w-24 sm:w-27 lg:w-40 hover:text-white transition" />
                            </a>
                            <a href="https://www.linkedin.com/in/kevin-lai-250339313/" target="_blank" rel="noopener noreferrer">
                                <IconLinkedin className="w-21 sm:w-27 lg:w-40 hover:text-white transition" />
                            </a>
                        </div>
                        <div className="flex flex-row flex-wrap gap-8">
                            <a href="https://www.instagram.com/kevinlai483/" target="_blank" rel="noopener noreferrer">
                                <IconInstagram className="w-21 sm:w-27 lg:w-40 hover:text-white transition" />
                            </a>
                            <a href="https://clovesandcinnamon3.wordpress.com/" target="_blank" rel="noopener noreferrer">
                                <IconWordPress className="w-21 sm:w-27 lg:w-40 hover:text-white transition" />
                            </a>
                        </div>
                    </div>

                    <p className="text-center text-gray-400 px-6 sm:px-12 lg:px-30 mt-6 sm:mt-10 lg:mt-16">
                        Designed and built from scratch with React and Next.js, styled with Tailwind CSS, and deployed on AWS. Typography set in Inter and Space Grotesk.
                    </p>
                </div>
            </section>
            </FadeIn>
        </main>
    </div>
  );
}

